name: webview_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/                    # ← эта строка нужна
    - assets/web/index.html          # ← явно укажи главный файл
    - assets/web/error.html          # ← явно укажи главный файл
    - assets/web/kpt_start.html      # ← и все важные файлы
    - assets/web/kpt_bye_old.html
    - assets/web/kpt_bye_FULL.html
    - assets/web/kpt_bye.html
    - assets/web/index_FULL.html
    - assets/web/index_tmp.html
    - assets/web/info_12.html
    - assets/web/info_mechtatel.html
    - assets/web/style.css
    - assets/web/bootstrap/css/
    - assets/web/bootstrap/js/
    - assets/web/img/
    - assets/web/icons/
    - assets/web/webfonts/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon_KPT_GL.png"